### ISSUE TITLE
Typo in `Computation Pipeline/Normalization`?

### ISSUE THREAD

**Issue by Urhengulas** [Green-Software-Foundation/ief#151]
In the example of the Normalization step in the Computation Pipeline docs, there are following two tables:
- before normalization https://github.com/Green-Software-Foundation/ief/blob/3f011517bb70540591337ef4fc1e375cd283952a/docs/Computation%20Pipeline.md?plain=1#L158-L162
- after normalization https://github.com/Green-Software-Foundation/ief/blob/3f011517bb70540591337ef4fc1e375cd283952a/docs/Computation%20Pipeline.md?plain=1#L172-L178

I am wondering two things:
1. Should the timestamp in line 161 be `15:00` instead of `05:00` and the timestamp in line 162 be `25:00` instead of `10:00`? Otherwise I am not understanding how it is getting translated.
2. Why is there no entry for `20:00` in the second table? Are empty datapoints omitted?

Thank you for your work and for thoroughly documenting it!

**Comment by jmcook1186** [comment]
Hi @Urhengulas - yes you are right those are all typos - thanks for catching them. Feel free to raise a PR to fix? Otherwise we will fix it this afternoon.

Also pinging @jawache for visibility.

**Comment by Urhengulas** [comment]
Thank you for the swift answer! Will send a PR now
