### ISSUE TITLE
CLI can load models dynamically

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#209]
**What**: The ability to load a (set of) models from other places
**Why**: So we can consume models that are not built into the framework
**DoD**:
 - [ ] A user can npm install a model and then configure it in the IMPL to be used in a pipeline.
 - [ ] The model is loaded by the CLI dynamically and configured on initialization.
 - [ ] The model is then kept in mem for the duration of computation and called multiple times by different components in the tree.

**Comment by jawache** [comment]
## Thoughts

### Are you installing one model or a group of models?

I think there will be some libraries that are collections of models and other libraries that are just one default export model.

e.g. Microsoft will probably package all their models into one large library `npm install, microsoft.if.models` how do you pull in just one model from that library? microsoft.if.models.azure.vm? But other smaller models will just be the thing you install e.g. `npm install co2js` there isn't anything else just the library co2js

### If impls need models to run, then do they need a package.json?

```
npm install co2js
rimple --impl my-impl.yaml
```

To run my yaml I need co2js model installed.
I don't want to install it in my global npm registry so I will create a local one.
This means you will need a package.json perhaps with every impl?

```
my-impl/impl.yml
my-impl/package.json
```
Or maybe you can dynamically create a package.json from the impl file and then load that?

```
create-pacakge-json my-impl.yml 
npm install
rimple --impl my-impl.yaml
```

**Comment by jawache** [comment]
## Using a model from GitHub
npm install github:xxxxxxx
(boavizta-cpu-model is the name of the model in package.json)

Then to use in Impl.

```
- name: boavizta
  kind: ??
  path: boavizta-cpu-model
```

## Using a published model from npm
npm install @boavista/if-model
(@boavista/if-model is the name of the model in package.json)

Then to use in Impl.

```
- name: boavizta
  kind: ??
  path: @boavista/if-model
```

## Using a model that you are creating locally on your machine
(see https://www.geeksforgeeks.org/how-to-install-a-local-module-using-npm/)
npm install /path/to/my-model
(my-model is the name of the model in package.json) - i think! there is also a method using npm-link, need to investigate. This is the use case for someone developing a model locally on their computer.

Then to use in Impl.

```
- name: boavizta
  kind: ??
  path: my-model
```

## How to handle if a module has one or multiple models?

The default mode should be one npm module === one model, with default export (as it is now)

To support the case where a module might contain multiple models maybe the approach below works?

```
- name: azure-function
  model: AzureFunctionModel
  path: @microsoft/azure/if/models
```

The default export of @microsoft/azure/if/models is an object like so:

```
{
   "AzureFunctionModel" : Class name?,
   "AzureVMModel" : Class name?,
   "AzureAKSModel" : Class name?      
}
```

If the default export is an object, you need to specify which exact model you are loading with the "model" config param?

**Comment by narekhovhannisyan** [comment]
@jawache It will be better to keep the same convention for all kinds of models (one and multiple). Since we have ability to provide model name as below
```
name: azure-function
  model: AzureFunctionModel
  path: @microsoft/azure/if/models
  ```
  then exporting with default will make things even more complicated

**Comment by jawache** [comment]
@narekhovhannisyan that makes sense, do we need "kind" anymore?

**Comment by narekhovhannisyan** [comment]
@jawache it will make it easier to figure out which way to go. If there will be any noticeable changes in model and path configurations, then based on that we can do our decision on model selection and skip kind. But as for now let's keep it.
