### ISSUE TITLE
Using JSII for writing polyglot (multi-language) libraries

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#43]
### Discussed in https://github.com/Green-Software-Foundation/carbon-ql/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **jawache** June 12, 2023</sup>
Was speaking to someone today and they mentioned that AWS use a tool called JSII to create their CSDK. 
https://github.com/aws/jsii

JSII lets you write code in TypeScript and then transpiles it into Python, Java and .Net, see: https://aws.amazon.com/fr/blogs/opensource/generate-python-java-dotnet-software-libraries-from-typescript-source/

I think it could be a good solution to write the initial set of libraries for carbon-ql.</div>

**Comment by jawache** [comment]
We discussed last project call and @gnanakeethan will create some demo code using JSII so we can review on the call whether it might be a good initial framework to use.

**Comment by gnanakeethan** [comment]
https://github.com/aws/jsii/issues/369

**Comment by jawache** [comment]
Asim: AWS recommend this isn't used for high performance or long running processes, for those make language specific libraries. We would consider this mostly for single shot calculations.

**Comment by gnanakeethan** [comment]
Unable to return a promise from JSII

**Comment by jawache** [comment]
Thanks @gnanakeethan, re: "Using "object" as return type causes troubles in calling methods from the returned "object" in Typescript & Python." is the returned object from TypeScript translated into a normal Dict object in Python? Could you elaborate on what methods you want to call on object which do not function.

**Comment by jawache** [comment]
Hi @gnanakeethan could you elaborate on the object question above?
