### ISSUE TITLE
IMPL files from SCI case studies

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#55]
**What**: We need examples of real IMPLs for things we want to measure.
**Why**: So we can have some real values to calculate emissions for.
**SoW**:
- Generate a sample IMPL file for each case study listed here https://sci-guide.greensoftware.foundation/CaseStudies
- Each IMPL (once all required models are also implemented) if computed should result in the same value being automatically calculated as was manually calculated in the case studies.
- Deliverable is a set of yaml files in a folder called /impls in this repo, one for each of the case studies.

**Comment by srini1978** [comment]
Average CPU utilization was used to calculate Energy values.

Server utilization = 18.3922%
Number of hours = 1
Number of cores = 2
TDP = 205W (got by doing an approximation of the server used in managed service 2nd Generation Intel® Xeon® Platinum 8272CL (Cascade Lake)= 205 W ( https://ark.intel.com/content/www/us/en/ark/products/192482/intel-xeon-platinum-8270-processor-35-75m-cache-2-70-ghz.html)
TDP Coefficient = 0.32 ( this value was derived using the energy proportionality principle and reference data is got from here https://docs.google.com/spreadsheets/d/1Viv94rMKH-fJrfD9Nn9_qkiAg1PDfIfJUAHRX9slG7A/edit#gid=526989613

**Comment by srini1978** [comment]
FYI @jawache @gnanakeethan

**Comment by jawache** [comment]
Thanks @srini1978, I think after we agree (hopefully) the IMPL spec that we create an IMPL file to represent this use case and add that to the catalogue of use cases we need to code against.

**Comment by jawache** [comment]
We agreed on the call to make an IMPL to define this case study. 
The model is a very generic model that uses the Teads data, perhaps we can make the model so the params and power curve are part of the IMPL.

**Comment by srini1978** [comment]
The carbonQL project aims to build an automated way  for us to easily measure carbon emissions from software of all types - web based, desktop, mobile app etc. We plan to do this  by tapping into publicly available models (CCF, Boavista) as well as privately owned datasets. 

The project calculate these carbon emissions values based on SCI. 

We understand that many case studies were done for calculating SCI values for many types of software applications. Towards that, we would like to understand the parameters that were used for these case studies. Examples of parameters would be : CPU utilization, vCPU hours used, machine type and processor used (e.g Intel cascade lake processor, Skylake processor etc). These parameters would have been used to get the usage values of E, I and/or M.m 

This is a call  to owners and developers of those case studies to share these parameters or "telemetry" as we call it in carbonQL project.

**Comment by jawache** [comment]
@jmcook1186 assigned this to you for the next IEF meeting can you prepare a pull request with initial IMPLs to represent each of the case studies.

I'm expecting lots of questions :) feel free to fire away or we can schedule a call to explain them once you've dug into the case studies a little.
