### ISSUE TITLE
As a Kubernetes user, i want to be able to query the SCI of my k8s  infra & workload resources

### ISSUE THREAD

**Issue by yelghali** [Green-Software-Foundation/ief#65]
As a Kubernetes user, i want to be able to query the SCI of my k8s  infra & workload resources

**Comment by yelghali** [comment]
link to read the article : https://github.com/yelghali/carbon-ql/blob/patch-1/specs/carbon-ql-k8s-specification.md

pr in GSF repo :  https://github.com/yelghali/carbon-ql/blob/patch-1/specs/carbon-ql-k8s-specification.md

**Comment by jawache** [comment]
Thanks @yelghali I've sent you an email, let's try and sync up before the thu call to discuss how to merge this with the main spec!

**Comment by jawache** [comment]
Hi @yelghali, closing this issue to clean up - I believe we've found an approach which works best to bring all the threads into one.
