### ISSUE TITLE
Implement CI/CD for each PR

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#77]
**What**: Implement CI/CD for the IEF project
**Why**: So we can automate checks and improve our quality
**SoW**:
- [ ] Run typescript linters on the TS code on any PR
- [ ] Run any unit or integration tests on any PR

**NOTE**: dev is our main development branch.

**Comment by narekhovhannisyan** [comment]
[5c4cb1d](https://github.com/Green-Software-Foundation/ief/commit/5c4cb1de3b16e679ccfc7c78cc6e617945a208eb)
